/* ==========================================================================
   PPL Study Guide — shared data
   PPL_DATA.searchIndex  → powers the cross-page instant search (search.js)
   PPL_DATA.flashcards   → powers the flashcard deck (flashcards.js)
   Each is plain data so both features stay in sync from one source.

   searchIndex entry fields: t=title, p=page#anchor, topic, k=keywords,
   s=summary, cap=diagram/image caption text (figcaption + img alt) so the
   search also finds terms that only appear in a diagram. The `cap` values are
   derived from the page captions — if you change a caption, refresh them.
   ========================================================================== */
window.PPL_DATA = {
  /* ---- Search index: one entry per section across the site ---- */
  searchIndex: [
    // Aerodynamics
    { t: "The four forces", p: "aerodynamics.html#four-forces", topic: "Aerodynamics", k: "lift weight thrust drag equilibrium steady flight", s: "Lift = weight and thrust = drag in steady, unaccelerated flight.", cap: "The four forces on an airplane: lift acts upward, weight downward, thrust forward, and drag aft." },
    { t: "Parasite vs induced drag", p: "aerodynamics.html#drag", topic: "Aerodynamics", k: "parasite induced drag wingtip vortices L/D max drag curve angle of attack", s: "Parasite drag rises with speed; induced drag rises at high AoA / low speed." },
    { t: "Left-turning tendencies", p: "aerodynamics.html#left-turning", topic: "Aerodynamics", k: "p-factor torque spiraling slipstream gyroscopic precession right rudder climb", s: "P-factor, spiraling slipstream and torque all yaw/roll the airplane left." },
    { t: "Axes & flight controls", p: "aerodynamics.html#axes", topic: "Aerodynamics", k: "roll pitch yaw aileron elevator rudder longitudinal lateral vertical axis", s: "Roll/aileron, pitch/elevator, yaw/rudder about the three axes.", cap: "Longitudinal = length (nose to tail). · The three axes of rotation through an airplane's center of gravity: the longitudinal axis (roll, nose to tail), the lateral axis (pitch, wingtip to wingtip), and the vertical axis (yaw)." },
    { t: "Stability & the CG", p: "aerodynamics.html#stability", topic: "Aerodynamics", k: "stable static dynamic center of gravity center of pressure dihedral longitudinal forward cg more stable aft cg less stable at all speeds", s: "CG ahead of CP is stable; forward CG more stable, aft CG less stable at all speeds." },
    { t: "Stalls & spins", p: "aerodynamics.html#stalls-spins", topic: "Aerodynamics", k: "stall spin rectangular wing root tip 172 autorotation aileron effectiveness critical angle of attack remains constant unchanged any airspeed attitude stall speed factors weight load factor forward cg increases aft cg decreases altitude", s: "A wing stalls past its critical angle of attack (always constant) — at any airspeed; weight/CG/bank change stall SPEED, not the AoA." },
    { t: "Load factor", p: "aerodynamics.html#load-factor", topic: "Aerodynamics", k: "load factor g force bank turn stall speed 60 degrees 2g", s: "Load factor = G-force; increases in turns and raises stall speed.", cap: "The Vg diagram (flight envelope). · Vg diagram (flight envelope): load factor versus indicated airspeed, showing the normal operating range, caution range, never-exceed speed, stall speed line and gust lines." },
    { t: "Ground effect", p: "aerodynamics.html#ground-effect", topic: "Aerodynamics", k: "ground effect wingspan induced drag vortices float runway", s: "Within one wingspan of the surface, induced drag drops and the airplane floats.", cap: "A wingtip vortex — the source of induced drag. Near the ground the surface squashes these vortices, so the airplane \"floats.\" · Front view of an airplane: higher-pressure air under the wing curls up and around the wingtip toward the lower-pressure air on top, forming a wingtip vortex." },
    // Systems
    { t: "Propeller & engine", p: "systems.html#engine", topic: "Systems", k: "constant speed propeller blade angle throttle power manifold pressure gauge propeller control engine rpm tachometer magneto p-lead hot mag ignition switch ground self-powered engine runs after switch off treat prop live carburetor heat detonation pre-ignition mixture carb ice", s: "Constant-speed prop: throttle = power (manifold pressure), prop control = RPM; a broken magneto P-lead leaves the mag hot; carb heat enriches the mixture." },
    { t: "Magnetic compass errors", p: "systems.html#compass", topic: "Systems", k: "ANDS UNOS variation deviation south heavy dip acceleration turning error start of turn leaving north opposite south exaggerate lead lag northern southern hemisphere reverses", s: "ANDS (accel error) and UNOS (turn error); variation vs deviation; start-of-turn error reverses by hemisphere.", cap: "Turning toward the poles: the compass lags near North (so you lead the rollout) and leads near South — that's UNOS . · Turning error: near Magnetic North the compass lags the turn (lead the rollout); near Magnetic South the compass leads the turn (lag the rollout)." },
    { t: "Pitot-static system", p: "systems.html#pitot-static", topic: "Systems", k: "pitot static port airspeed altimeter vsi blocked alternate static source", s: "Pitot feeds the ASI; static feeds ASI, altimeter and VSI; blockages and effects.", cap: "Pitot → ASI only. Static → ASI + Altimeter + VSI. · Pitot-static plumbing: the pitot tube feeds only the airspeed indicator; the static port feeds the airspeed indicator, altimeter and vertical speed indicator." },
    { t: "Attitude indicator", p: "systems.html#attitude-indicator", topic: "Systems", k: "attitude indicator gyroscope gyro horizon bar miniature airplane fixed in space read pitch bank relative to horizon line only rotates around", s: "Gyro holds the horizon bar fixed; read pitch/bank from the little airplane vs the horizon." },
    { t: "Types of altitude", p: "systems.html#altitudes", topic: "Systems", k: "indicated true MSL absolute AGL pressure density altitude 29.92 inch hg", s: "True = MSL, absolute = AGL, pressure altitude at 29.92." },
    { t: "Airspeeds: IAS, CAS, TAS, GS", p: "systems.html#airspeeds", topic: "Systems", k: "indicated calibrated true airspeed ground speed IAS CAS TAS GS position installation error air density altitude temperature wind e6b e6-b wind side 2 percent per 1000 ft v-speeds stall convert difference", s: "IAS → CAS (position error) → TAS (air density) → GS (wind); you fly IAS." },
    // Airspace
    { t: "Airspace overview (wedding cake)", p: "airspace.html#overview", topic: "Airspace", k: "controlled uncontrolled class A B C D E G cross section two-way radio", s: "How controlled airspace stacks up from A through G.", cap: "The airspace classes in cross-section. · Cross-section of US airspace classes A through G with a table of entry requirements, VFR visibility minimums, and VFR cloud clearance for each class." },
    { t: "Classes A–G", p: "airspace.html#classes", topic: "Airspace", k: "class A B C D E G IFR clearance two way radio contact ceiling bracket", s: "Each class, its entry requirement and chart color." },
    { t: "VFR weather minimums & 152/111", p: "airspace.html#vfr-minimums", topic: "Airspace", k: "vfr minimums cloud clearance 152 111 visibility 3sm 5sm clear of clouds 91.155", s: "152 = 1000/500/2000; 111 = 1000/1000/1SM; full minimums table.", cap: "Cloud-clearance and visibility minimums by class. · Airspace classes A through G showing the VFR cloud clearance distances and visibility for each: Class B clear of clouds 3SM; C/D/E below 10,000 is 3-152; E/G at or above 10,000 is 5-111; Class G day below 1,200 AGL is 1SM clear of clouds." },
    { t: "Special VFR (SVFR)", p: "airspace.html#special-vfr", topic: "Airspace", k: "special VFR SVFR clear of clouds 1 SM statute mile flight ground visibility surface area class B C D E below 10000 MSL night instrument rating IFR equipped 91.205 request ATC clearance NO SVFR appendix D prohibit fixed-wing", s: "Request from ATC to enter/leave a surface area below VFR mins: 1 SM, clear of clouds; night SVFR needs an instrument rating + IFR aircraft." },
    { t: "Special-use airspace", p: "airspace.html#special-use", topic: "Airspace", k: "prohibited restricted MOA military warning alert area", s: "Prohibited, restricted, MOA, warning and alert areas." },
    { t: "Transponders & Mode C veil", p: "airspace.html#equipment", topic: "Airspace", k: "mode c veil 30 nm ADS-B transponder anti-collision lights 10000", s: "30 NM veil around Class B, surface to 10,000 MSL.", cap: "ADS-B Out / Mode C is required: in Class E at 10,000 ft MSL and above (CONUS), in and above Class C up to 10,000 ft MSL, and in and above Class B including the 30 NM veil around it." },
    // Airports
    { t: "Traffic pattern", p: "airports.html#pattern", topic: "Airports", k: "traffic pattern upwind crosswind downwind base final 45 entry left traffic windsock", s: "Left traffic; enter downwind at 45 degrees; the five legs.", cap: "All turns are to the left unless right traffic is published — enter the downwind on the 45° . · A windsock is a carrot — take off and land the way you'd eat it: small → large (toward the fat end, into the wind). · The pointy end indicates where the wind is coming from — and the direction in which aircraft should take off and land. · A runway layout with a tetrahedron landing-direction indicator inside a segmented circle; the tetrahedron's pointed end points into the wind." },
    { t: "Runway numbers & signs", p: "airports.html#runways", topic: "Airports", k: "runway number magnetic heading red sign yellow sign hold short LAHSO wildlife refuge threshold bar demarcation bar displaced threshold white yellow blast pad chevron ILS hold position runway holding position non-movement area boundary vehicle roadway intermediate holding position taxiway direction sign taxiway location sign", s: "Runway numbers come from the magnetic heading; red = on runway, yellow = direction.", cap: "Red = mandatory — hold short of Runway 22. · Black = location — you are on Runway 22. · Yellow + arrow = direction to a taxiway. · Airport surface diagram labeling: B an ILS hold-position marking, C white vehicle roadway markings, D a runway holding-position marking, E an intermediate holding-position marking, F a taxiway location sign, and G a non-movement area boundary marking on a taxiway." },
    { t: "Taxiing", p: "airports.html#taxiing", topic: "Airports", k: "taxi taxiing wind control aileron elevator tailwind headwind climb into dive away taxi lights blue edge green centerline night park facing into the wind parking secure airframe", s: "Climb into a headwind, dive away from a tailwind; park facing into the wind; taxi lights: blue edge, green centerline.", cap: "At night: blue = taxiway edge lights; green = taxiway centerline lights. · Taxi lights at night: blue lights line both edges of the taxiway and green lights run down the taxiway centerline." },
    { t: "PAPI vs VASI glidepath", p: "airports.html#glidepath", topic: "Airports", k: "PAPI VASI red white glidepath 3 degree stabilized approach speed +10 -5 KIAS landing speed POH soft field same normal short field gusty wind add half gust factor soft field takeoff Vx best angle climb ground effect", s: "Red over white, you're alright; 3 degree stabilized approach; soft-field = normal approach speed; short-field gusts add half the gust factor; soft-field takeoff climbs at Vx." },
    { t: "Pilot-controlled lighting", p: "airports.html#pilot-lighting", topic: "Airports", k: "pilot controlled lighting runway lights mic clicks key microphone 7 5 3 brightness intensity 15 minutes CTAF night", s: "Key the mic — 7/5/3 clicks for high/medium/low; on for 15 minutes." },
    { t: "Wake turbulence", p: "airports.html#wake-turbulence", topic: "Airports", k: "wake turbulence wingtip vortices heavy clean slow rotate touchdown 2 minutes light quartering tailwind", s: "Vortices worst heavy/clean/slow; land beyond, rotate before, wait 2 minutes." },
    // ATC
    { t: "Non-towered communications", p: "atc.html#non-towered", topic: "ATC", k: "non-towered nontowered CTAF common traffic advisory frequency self-announce UNICOM MULTICOM 122.9 airport advisory winds active runway request satellite airport class c d contact ATC after takeoff inbound 10 miles out no tower FSS", s: "Self-announce on CTAF; UNICOM/FSS give an airport advisory; MULTICOM is always 122.9 (self-announce 10 mi out inbound)." },
    { t: "Transponder & squawk codes", p: "atc.html#transponder", topic: "ATC", k: "squawk 1200 7500 7600 7700 mode c ADS-B VFR 121.5 122.2", s: "1200 VFR, 7500 hijack, 7600 lost comms, 7700 emergency." },
    { t: "Light-gun signals", p: "atc.html#light-gun", topic: "ATC", k: "light gun signal green red white steady flashing lost comms steady red stay where you are flashing red go away", s: "Tower light-gun signals when the radio fails.", cap: "Tower light-gun signals. · Light-gun signals from the tower: steady green = cleared to land/takeoff; flashing green = return to land / cleared to taxi; steady red = give way / stop; flashing red = airport unsafe / leave the runway; flashing white = return to starting point; alternating red and green = extreme caution." },
    // Performance
    { t: "V-speeds", p: "performance.html#v-speeds", topic: "Performance", k: "v-speeds Va Vno Vne Vso Vs1 Vfe Vx Vy maneuvering weight airspeed arcs", s: "Va depends on weight; ASI color arcs and key V-speeds.", cap: "Airspeed indicator with V-speed markings: white arc (flap range) from Vso (stall, flaps down) to Vfe (flaps-extended speed); green arc (normal operating range) from Vs1 (stall, clean) to Vno (max structural cruising); yellow caution arc up to the red Vne (never exceed) line." },
    { t: "Four performance factors", p: "performance.html#factors", topic: "Performance", k: "altitude temperature pressure humidity density high low pressure", s: "Altitude, temperature, pressure, humidity all change air density.", cap: "The four key performance factors, all driven by air density (thinner air = worse performance): higher altitude, higher temperature, lower pressure, and higher humidity each worsen performance; lower altitude, lower temperature, higher pressure, and lower humidity each improve it." },
    { t: "Pressure & density altitude", p: "performance.html#density-altitude", topic: "Performance", k: "pressure altitude density altitude formula 29.92 120 OAT true airspeed 1 inch hg 15C indicated field elevation", s: "Density altitude = pressure altitude corrected for temperature.", cap: "A POH takeoff/landing chart. · Takeoff/landing performance chart: start at outside air temperature, go up to pressure altitude, across to weight, to the wind component, then to obstacle height to read the required distance." },
    { t: "Weight & balance", p: "performance.html#weight-balance", topic: "Performance", k: "weight balance CG center of gravity moment arm datum fuel 6 lbs limits", s: "Keep CG within limits; moment = weight × arm, CG = total moment ÷ total weight.", cap: "Side view of a light airplane showing the center of lift acting upward near the wing, the weight acting downward at the center of gravity ahead of it, and a downward tail force that balances the nose-down tendency." },
    // Regulations
    { t: "Documents & equipment (ARROW/ATOMATOFLAMES)", p: "regulations.html#documents", topic: "Regulations", k: "ARROW ATOMATOFLAMES FLAPS NWKRAFT required equipment documents day night vfr 91.205 91.103 only airworthiness certificate displayed visible 91.203", s: "ARROW docs (only airworthiness cert displayed); ATOMATOFLAMES day, FLAPS night; NWKRAFT preflight." },
    { t: "Right-of-way & minimum altitudes", p: "regulations.html#right-of-way", topic: "Regulations", k: "right of way head on turn right converging overtaking landing final approach lower altitude in distress congested 1000 2000 500 agl 91.113 91.119", s: "Turn right head-on; 1000 over cities, 500 elsewhere.", cap: "Minimum safe altitudes by area — and anywhere , high enough to land safely if the engine fails. · Right-of-way rules: approaching head-on, both aircraft turn right; converging traffic gives way to the aircraft on its right; when overtaking, pass and keep to the right. · Minimum safe altitudes: congested areas 1,000 ft above the highest obstacle within 2,000 ft; other areas 500 ft AGL; over open water or sparsely populated areas, 500 ft from any person, vessel, or structure." },
    { t: "VFR cruising altitudes", p: "regulations.html#cruising-altitudes", topic: "Regulations", k: "cruising altitude east odd west even 500 magnetic course 3000 agl 91.159", s: "East odd + 500, west even + 500, above 3,000 AGL.", cap: "Pick by magnetic course (above 3,000′ AGL). Mnemonic: \"East is odd; West is even\" — then add 500 ft for VFR." },
    { t: "Speed limits", p: "regulations.html#speed-limits", topic: "Regulations", k: "speed limit 250 200 knots 10000 2500 agl class b 91.117", s: "250 below 10k; 200 below 2,500 AGL near C/D and under B.", cap: "Speed limits: no restriction above 10,000 ft MSL; 250 KIAS or less below 10,000 ft; 200 KIAS or less beneath a Class B shelf and within 4 NM below 2,500 ft of a Class C or D airport. Inside Class B itself, the limit stays 250 KIAS." },
    { t: "VFR fuel reserves", p: "regulations.html#fuel-reserves", topic: "Regulations", k: "fuel reserve day 30 night 45 minutes 91.151", s: "Day +30 min, night +45 min." },
    { t: "Inspections", p: "regulations.html#inspections", topic: "Regulations", k: "annual 100 hour transponder 24 ELT 12 pitot static inspection 121.5 243 406 alteration repair return to service test flight passengers 91.407 91.207 test only first 5 minutes after the hour", s: "Annual 12 mo, 100-hr for hire, transponder 24 mo, ELT 12 mo (test only first 5 min after the hour)." },
    { t: "Currency & medical", p: "regulations.html#currency-medical", topic: "Regulations", k: "flight review 24 months 90 days 3 takeoffs landings medical basicmed 48 type rating 12500", s: "Flight review 24 mo; 3 T/O & landings in 90 days; medicals." },
    { t: "Alcohol & aerobatic limits", p: "regulations.html#alcohol-aerobatic", topic: "Regulations", k: "alcohol 8 hours bottle throttle 0.04 BAC parachute 30 pitch 60 bank repack 180 days rigger", s: "8 hours, 0.04 BAC; parachute beyond 30/60 (repack 180 days)." },
    { t: "Emergency authority & reporting", p: "regulations.html#emergency-reporting", topic: "Regulations", k: "emergency reporting authority NTSB FAA ATC aircraft accident 10 days overdue missing 7 days serious incidents flight control fire collision crewmember immediate notification deviation part 91 rule 48 hours facility manager FAA administrator priority 91.3 91.123 substantial damage 830 property 25000 preserve wreckage move only protect nose landing gear single engine fairing cowling prop blade wingtip incident no report needed accident vs incident", s: "Who reports to whom: NTSB (accident 10-day, overdue 7-day, serious incidents), FAA for a Part 91 deviation, ATC 48 hr after a deviation; report an accident but not an ordinary incident; plus substantial damage and preserving the wreckage." },
    { t: "Categories & classes", p: "regulations.html#categories-classes", topic: "Regulations", k: "category class airmen aircraft normal utility acrobatic single engine land helicopter rotorcraft airplane airworthiness advisory circular AC non-binding mission machine specs flip", s: "The same words flip: an aircraft's class = an airman's category (Airplane/Rotorcraft)." },
    { t: "Training endorsements", p: "regulations.html#endorsements", topic: "Regulations", k: "endorsement high performance 200 hp complex retractable gear flaps controllable pitch prop high altitude 25000 pressurized tailwheel type rating 61.31", s: "High-performance >200 hp; complex; high-altitude >25,000 ft; tailwheel." },
    // Weather
    { t: "Stability & lapse rate", p: "weather.html#stability", topic: "Weather", k: "stable unstable lapse rate stratus cumulus condensation level dew point 2C", s: "Stable = stratus/poor vis; unstable = cumulus/showers.", cap: "Stable air → flat, layered stratiform clouds. · Unstable air → puffy, towering cumuliform clouds. · Stratiform clouds form in stable air: a rising thermal cools to the surrounding air temperature and stops climbing, so the cloud spreads out flat and layered. · Cumuliform clouds form in unstable air: a rising thermal stays warmer than the surrounding air, so it keeps climbing and the cloud builds up tall and puffy." },
    { t: "Pressure systems", p: "weather.html#pressure-systems", topic: "Weather", k: "low high pressure counterclockwise clockwise rising sinking buys ballot high to low look out below", s: "Low = CCW inflow rising; high = CW outflow sinking.", cap: "Northern Hemisphere. With your back to the wind, low pressure is on your left, high pressure on your right." },
    { t: "Thunderstorms", p: "weather.html#thunderstorms", topic: "Weather", k: "thunderstorm moisture lifting unstable towering cumulus mature dissipating stages downdraft gust front outflow wind blows from storm direction", s: "Ingredients: moisture, lift, instability; 3 stages; downdraft gust front (wind from the storm)." },
    { t: "Fronts", p: "weather.html#fronts", topic: "Weather", k: "warm cold stationary occluded front wind shift change direction showers thunderstorms gusty low ceilings steady rain drizzle visibility lingers occlusion clearing", s: "Four fronts and the weather each brings; wind direction changes when you cross any front." },
    { t: "Fog & temperature inversions", p: "weather.html#fog", topic: "Weather", k: "radiation advection upslope fog temperature inversion poor visibility", s: "Radiation, advection and upslope fog; inversions trap air." },
    { t: "Upper-air hazards", p: "weather.html#hazards", topic: "Weather", k: "tropopause cirrus jet stream clear air turbulence wind shear icing 25 kts structural airframe visible moisture carburetor icing clear air", s: "Tropopause, CAT, wind shear, cirrus and icing." },
    // Weather Reports
    { t: "METAR & TAF", p: "weather-reports.html#metar-taf", topic: "Weather Reports", k: "metar taf observation forecast decode zulu wind visibility altimeter P6SM", s: "METAR = observation, TAF = forecast (vis to 6 SM)." },
    { t: "Sky cover & weather codes", p: "weather-reports.html#sky-cover", topic: "Weather Reports", k: "CLR FEW SCT BKN OVC ceiling eighths oktas BR FG RA DZ SN TS HZ VC", s: "CLR to OVC sky cover; ceiling is first BKN/OVC; weather codes." },
    { t: "Winds & temps aloft", p: "weather-reports.html#winds-aloft", topic: "Weather Reports", k: "winds aloft decode 730649 over 100 knots add 50 subtract 100 temperature", s: "Over 100 kt: +50 to direction, -100 from speed." },
    { t: "AIRMET, SIGMET & briefings", p: "weather-reports.html#advisories", topic: "Weather Reports", k: "airmet sierra tango zulu sigmet convective outlook standard abbreviated briefing request provide pilot vfr ifr aircraft identification n-number flight service 122.2 significant weather prognostic prog chart altitude blocks areas to avoid", s: "AIRMET (light), SIGMET (severe), outlook briefing ≥ 6 hrs; when you call, give pilot/VFR-IFR/aircraft ID." },
    // Navigation
    { t: "Pilotage & dead reckoning", p: "navigation.html#basics", topic: "Navigation", k: "pilotage dead reckoning landmarks heading time speed distance chart latitude", s: "Landmarks vs computed position; chart tick = 30 min = 0.5 deg." },
    { t: "VOR navigation", p: "navigation.html#vor", topic: "Navigation", k: "VOR radial CDI needle deflection TO FROM perpendicular position fix magnetic VOT receiver check test 4 degrees", s: "Radials are magnetic; needle right = course right; cross two radials.", cap: "A CDI : set the course with the OBS knob, then fly toward the needle to center it. The TO/FR flag shows whether the course leads to or from the station. · Two course deviation indicators (CDIs): each has an OBS knob to select a course, a vertical needle that deflects left or right to show which way the course lies, and a TO/FR flag." },
    { t: "GPS & RAIM", p: "navigation.html#gps", topic: "Navigation", k: "GPS limitation heading track RAIM integrity accuracy", s: "GPS doesn't know heading; RAIM checks accuracy." },
    { t: "NAVAID symbols", p: "navigation.html#navaids", topic: "Navigation", k: "VOR VORTAC VOR DME hexagon symbol true virgins make dull companions variation deviation", s: "Hexagon = VOR; +tabs = VORTAC; in a square = VOR/DME." },
    // Navigation Planning
    { t: "Course vs. heading", p: "navigation-planning.html#course-heading", topic: "Navigation Planning", k: "true course TC true heading TH magnetic heading MH wind correction angle WCA variation over the ground nose points chart plot", s: "TC (over the ground) → +wind → TH → +variation → MH." },
    { t: "The wind triangle", p: "navigation-planning.html#wind-triangle", topic: "Navigation Planning", k: "wind triangle vector air vector ground vector wind vector true heading true airspeed true course groundspeed wind correction angle WCA crab resultant", s: "Air vector + wind = ground vector; the angle between them is the WCA." },
    { t: "Magnetic variation", p: "navigation-planning.html#variation", topic: "Navigation Planning", k: "variation isogonic agonic east is least west is best add subtract true magnetic heading", s: "East is least (subtract), west is best (add) — true to magnetic." },
    { t: "Speed, distance & time", p: "navigation-planning.html#speed-distance-time", topic: "Navigation Planning", k: "speed distance time triangle dead reckoning groundspeed knot nautical mile per hour E6-B formula", s: "D = S × T; 1 knot = 1 NM per hour.", cap: "Distance on top; speed and time on the bottom. Side-by-side = multiply; one over the other = divide." },
    // Human Factors
    { t: "Oxygen & hypoxia", p: "human-factors.html#hypoxia", topic: "Human Factors", k: "hypoxia 8000 oxygen 12500 14000 15000 hypoxic hypemic stagnant histotoxic water", s: "Hypoxia above ~8,000 ft; supplemental O2 rules." },
    { t: "Carbon monoxide", p: "human-factors.html#carbon-monoxide", topic: "Human Factors", k: "carbon monoxide CO loss of muscular power heater exhaust", s: "CO causes loss of muscular power; from the cabin heater." },
    { t: "Night vision", p: "human-factors.html#night-vision", topic: "Human Factors", k: "night vision off-center peripheral scan dark adapt rods", s: "Use off-center viewing at night; the center of vision is weak." },
    { t: "Illusions & disorientation", p: "human-factors.html#illusions", topic: "Human Factors", k: "haze illusion farther IMC spatial disorientation acceleration climb runway slope leans coriolis vestibular head movement", s: "Haze = farther; accel/decel feel like climb/descent; the leans & Coriolis." },
    { t: "Fitness to fly (IMSAFE)", p: "human-factors.html#fitness", topic: "Human Factors", k: "IMSAFE illness medication stress alcohol fatigue emotion eating checklist", s: "IMSAFE personal go/no-go checklist." },
    // FAR/AIM
    { t: "FAR/AIM: what to read", p: "far-aim.html#roadmap", topic: "FAR/AIM", k: "far aim part 1 43 61 91 830 chapter roadmap what to read sections study", s: "Roadmap of the key FAR parts and AIM chapters — and where each is taught." },
    { t: "Definitions: the three 'nights'", p: "far-aim.html#definitions", topic: "FAR/AIM", k: "night definition civil twilight calendar month logging position lights sunset sunrise part 1", s: "Logging vs. passenger-currency vs. position-lights night; calendar month." },
    { t: "Preventive maintenance you may do", p: "far-aim.html#preventive-maintenance", topic: "FAR/AIM", k: "preventive maintenance part 43 appendix A oil tires spark plugs safety belts bulbs battery owner logbook entry maintenance record description date signature certificate number kind of certificate held approving 43.9", s: "Oil, tires, belts, bulbs, plugs — owner-allowed jobs; log a description, date, and the signer's signature, certificate number & kind of certificate." },
    { t: "Private-pilot privileges & cost-sharing", p: "far-aim.html#privileges", topic: "FAR/AIM", k: "private pilot privileges limitations pro rata share compensation hire fuel oil airport rental common purpose change of address 30 days charitable charity nonprofit community event donate 500 hours part 61", s: "Pro-rata cost sharing (fuel/oil/airport/rental); no hire; charity flights; 30-day address." },
    { t: "Operating rule extras (PIC, INOP, SVFR)", p: "far-aim.html#operating-extras", topic: "FAR/AIM", k: "PIC pilot in command authority airworthy inoperative equipment INOP placard altimeter 100 nm special VFR SVFR dropping objects 91.15 two-way radio tower 4 nm 2500 agl satellite emergency deviate part 91", s: "PIC authority/airworthiness, inop equipment, altimeter 100 NM, special VFR." },
    { t: "Airport beacons", p: "far-aim.html#airport-lighting", topic: "FAR/AIM", k: "airport beacon colors white green land water yellow heliport military daytime beacon IFR rotating aim chapter 2", s: "White+green = land airport; daytime beacon = poor weather." },
    // ACS
    { t: "ACS: Airworthiness extras (AD/SAIB, MEL/KOEL)", p: "acs.html#airworthiness", topic: "ACS", k: "airworthiness directive AD mandatory SAIB special airworthiness information bulletin advisory special flight permit ferry permit MEL minimum equipment list KOEL kinds of operation", s: "AD vs SAIB; special flight permit; MEL vs KOEL." },
    { t: "ACS: Flight-plan extras (activate/close, intercept)", p: "acs.html#planning", topic: "ACS", k: "VFR flight plan activate close flight service search and rescue SAR 30 minutes ETA inflight intercept procedures 121.5", s: "Activate/close a VFR flight plan; SAR; intercept procedures." },
    { t: "ACS: Airspace extras (TFR, SFRA, MTR)", p: "acs.html#airspace", topic: "ACS", k: "TFR temporary flight restriction SFRA special flight rules area DC MTR military training route IR VR other airspace", s: "TFRs, SFRAs, and military training routes." },
    { t: "ACS: Aeronautical decision-making (ADM)", p: "acs.html#adm", topic: "ACS", k: "ADM hazardous attitudes antidotes anti-authority impulsivity invulnerability macho resignation PAVE DECIDE risk management situational awareness bias", s: "5 hazardous attitudes + antidotes; PAVE; DECIDE." },
    { t: "ACS: Runway status lights (RWSL)", p: "acs.html#lighting", topic: "ACS", k: "runway status lights RWSL REL runway entrance lights THL takeoff hold lights red automatic", s: "RWSL: automatic red REL/THL; a red light overrides a clearance." },
    { t: "ACS: Diversion & lost procedures", p: "acs.html#diversion-lost", topic: "ACS", k: "diversion alternate divert lost procedures five c climb communicate confess comply conserve 7700", s: "Diversion technique; lost = the 5 C's." },
    { t: "ACS: Spin recovery", p: "acs.html#recovery", topic: "ACS", k: "spin recovery PARE power ailerons rudder elevator", s: "PARE spin recovery." },
    // Testing Supplement
    { t: "Testing supplement cheatsheet (what to look up)", p: "supplement.html", topic: "Supplement", k: "testing supplement FAA-CT-8080-2 8080 figures legends look up lookup akts airman knowledge test provided booklet reference memorize vs which figure", s: "Which study topics you can look up in the test supplement (figures/legends) vs. must memorize." },
    { t: "Supplement: figures for performance, weather & charts", p: "supplement.html#performance", topic: "Supplement", k: "density altitude figure 8 weight balance 32 crosswind 36 metar 12 taf 15 winds aloft 17 sectional legend 1 VOR 28 wind triangle 68 attitude indicator 7 airport signs markings 64 65 VASI 47", s: "Figure numbers for density altitude, W&B, METAR/TAF, sectional charts, VOR and more." },
    { t: "Supplement: Appendix 1 legends (chart & airport keys)", p: "supplement.html#legends", topic: "Supplement", k: "appendix 1 legend 1 sectional chart legend 2 19 chart supplement directory legend 9 pilot control airport lighting clicks 7 5 3 magnetic variation isogonic navaid symbols airspace colors towered magenta CTAF UNICOM ATIS LAHSO declared distance", s: "What each supplement legend keys: sectional symbols, airport data, pilot-controlled lighting & PAPI/VASI (Legend 9), magnetic variation (Legend 1)." },
  ],

  /* ---- Flashcards ---- */
  flashcards: [
    // Aerodynamics
    { topic: "Aerodynamics", q: "What are the four forces of flight?", a: "Lift, Weight, Thrust, Drag." },
    { topic: "Aerodynamics", q: "In steady, unaccelerated flight, what is in balance?", a: "Lift = Weight, and Thrust = Drag." },
    { topic: "Aerodynamics", q: "Three causes of left-turning tendency?", a: "P-factor, spiraling slipstream, and torque (Newton's 3rd law). Gyroscopic precession is a 4th." },
    { topic: "Aerodynamics", q: "When are torque and P-factor strongest?", a: "Low airspeed, high power, high angle of attack — i.e. the climb." },
    { topic: "Aerodynamics", q: "How does parasite drag change with airspeed?", a: "It increases with speed (with the square of speed)." },
    { topic: "Aerodynamics", q: "When is induced drag greatest?", a: "At high angle of attack / low airspeed." },
    { topic: "Aerodynamics", q: "What is induced drag?", a: "The rearward horizontal component of lift, plus wingtip vortices — the by-product of making lift." },
    { topic: "Aerodynamics", q: "What happens at L/D max?", a: "Total drag is lowest and lift-to-drag is best — best glide / max endurance speed." },
    { topic: "Aerodynamics", q: "What defines a spin?", a: "Both wings stalled, but one more than the other, causing autorotation." },
    { topic: "Aerodynamics", q: "On a 172's rectangular wing, which part stalls first?", a: "The wing root (higher AoA) — so ailerons stay effective at the start of the stall." },
    { topic: "Aerodynamics", q: "Roll uses which control and axis?", a: "Ailerons, about the longitudinal axis." },
    { topic: "Aerodynamics", q: "Pitch uses which control and axis?", a: "Elevator, about the lateral axis." },
    { topic: "Aerodynamics", q: "Yaw uses which control and axis?", a: "Rudder, about the vertical axis." },
     { topic: "Aerodynamics", q: "Where should the CG be relative to the CP?", a: "Ahead of (in front of) the center of pressure — and the main wheels." },
     { topic: "Aerodynamics", q: "How does loading to the most aft CG affect stability?", a: "It makes the airplane less stable at all speeds (and harder to recover from stalls/spins)." },
     { topic: "Aerodynamics", q: "What does wing dihedral provide?", a: "Lateral (roll) stability." },
    { topic: "Aerodynamics", q: "Load factor in a 60° bank?", a: "2.0 G." },
    { topic: "Aerodynamics", q: "Load factor matters for which maneuver?", a: "Turns/banks — straight-and-level is always 1 G." },
    { topic: "Aerodynamics", q: "Ground effect is strongest within what height?", a: "About one wingspan above the surface (induced drag drops)." },
    { topic: "Aerodynamics", q: "What raises or lowers stall speed?", a: "Higher with more weight, load factor (steep bank/pull-up), or forward CG; lower with an aft CG. Altitude → no change in indicated stall speed." },
    { topic: "Aerodynamics", q: "Does weight, CG, bank, or altitude change the critical angle of attack?", a: "No — the critical AoA stays constant; those only change the stall SPEED." },
    // Systems
    { topic: "Systems", q: "What is a constant-speed propeller?", a: "A propeller whose blade angle (pitch) can be adjusted." },
    { topic: "Systems", q: "On a constant-speed prop, what do the throttle and propeller control set?", a: "Throttle = power output (shown on the manifold pressure gauge); propeller control = engine RPM (tachometer)." },
    { topic: "Systems", q: "How does the ignition switch stop a magneto, and what's the hazard?", a: "It grounds the magneto through its P-lead. A broken/disconnected P-lead ground leaves the mag hot, so the engine can fire with the switch OFF — treat the prop as live." },
    { topic: "Systems", q: "What does carburetor heat do to the mixture?", a: "It enriches it — warm air is less dense, so more fuel-to-air." },
    { topic: "Systems", q: "Detonation vs pre-ignition?", a: "Detonation = the mixture explodes instead of burning; pre-ignition = it ignites before the spark (hot spot)." },
    { topic: "Systems", q: "Compass: what does ANDS mean?", a: "Accelerate North, Decelerate South (acceleration error on E/W headings)." },
    { topic: "Systems", q: "Compass: what does UNOS mean?", a: "Undershoot North, Overshoot South (turning error to N/S)." },
    { topic: "Systems", q: "At the start of a turn, how does the compass behave leaving North vs South?", a: "Northern Hemisphere: leaving North it first swings the opposite way (then lags); leaving South it exaggerates the turn (leads). Reversed in the Southern Hemisphere." },
    { topic: "Systems", q: "Variation vs deviation?", a: "Variation = true vs magnetic north (location). Deviation = error from metal/electronics in the airplane." },
    { topic: "Systems", q: "A blocked static port affects which instruments?", a: "Altimeter freezes, VSI sticks, airspeed reads inaccurately." },
    { topic: "Systems", q: "Which instrument does the pitot tube feed?", a: "Only the airspeed indicator." },
    { topic: "Systems", q: "Which instruments does the static port feed?", a: "Airspeed indicator, altimeter, and VSI." },
    { topic: "Systems", q: "On the attitude indicator, what do you read pitch and bank from?", a: "Only the miniature airplane's position relative to the horizon line — not any other marking. The horizon rotates around the fixed little airplane." },
    { topic: "Systems", q: "True altitude is referenced to what?", a: "Mean sea level (MSL)." },
    { topic: "Systems", q: "Absolute altitude is referenced to what?", a: "Above ground level (AGL)." },
    { topic: "Systems", q: "Pressure altitude is read with the altimeter set to?", a: "29.92 in Hg." },
    { topic: "Systems", q: "1 inch of Hg is about how many feet?", a: "About 1,000 ft." },
    { topic: "Systems", q: "IAS → CAS → TAS → GS: what correction does each step add?", a: "IAS→CAS: instrument/position error. CAS→TAS: air density (altitude + temperature). TAS→GS: wind." },
    { topic: "Systems", q: "Which airspeed do you actually fly (V-speeds, stalls)?", a: "Indicated (IAS) — the wing stalls at the same IAS at any altitude." },
    { topic: "Systems", q: "How does TAS compare with IAS as you climb?", a: "TAS gets higher than IAS (thinner air) — about +2% per 1,000 ft; at sea level on a standard day IAS ≈ CAS ≈ TAS." },
    { topic: "Systems", q: "Ground speed vs true airspeed?", a: "GS = TAS adjusted for wind: headwind → GS less than TAS; tailwind → GS more than TAS." },
    // Airspace
    { topic: "Airspace", q: "Class A altitudes and rule?", a: "18,000 ft MSL up to FL600, IFR only." },
    { topic: "Airspace", q: "Class B VFR minimums and entry?", a: "3 SM visibility, clear of clouds, and an explicit ATC clearance." },
    { topic: "Airspace", q: "What does the '152' cloud clearance mean?", a: "1,000 ft above, 500 ft below, 2,000 ft horizontal." },
    { topic: "Airspace", q: "What does the '111' cloud clearance mean?", a: "1,000 ft above, 1,000 ft below, 1 SM horizontal (E/G at/above 10,000 MSL)." },
    { topic: "Airspace", q: "What's required to enter Class C?", a: "Establish two-way radio communication." },
    { topic: "Airspace", q: "Class G day, below 1,200 AGL minimums?", a: "1 SM visibility, clear of clouds." },
    { topic: "Airspace", q: "Class G night minimums?", a: "3 SM visibility and '152' (1,000/500/2,000)." },
    { topic: "Airspace", q: "Mode C veil dimensions?", a: "30 NM around Class B, surface to 10,000 ft MSL." },
    { topic: "Airspace", q: "Prohibited vs Restricted airspace?", a: "Prohibited = no flight ever; Restricted = enter only when inactive or with permission." },
    // Airports
    { topic: "Airports", q: "Standard pattern direction and entry?", a: "Left traffic; enter the downwind at a 45° angle." },
    { topic: "Airports", q: "Name the five traffic-pattern legs.", a: "Upwind, crosswind, downwind, base, final." },
    { topic: "Airports", q: "What do runway numbers represent?", a: "The magnetic heading with the last digit dropped (toward magnetic north)." },
    { topic: "Airports", q: "A red runway sign means?", a: "You are ON that runway (location sign)." },
    { topic: "Airports", q: "PAPI showing 2 red + 2 white means?", a: "On glidepath ('red over white, you're alright')." },
    { topic: "Airports", q: "PAPI showing all red means?", a: "Too low ('red over red, you're dead')." },
    { topic: "Airports", q: "Recommended stabilized-approach glidepath?", a: "About 3°." },
    { topic: "Airports", q: "What does LAHSO stand for?", a: "Land And Hold Short Operations." },
    { topic: "Airports", q: "When is wake turbulence strongest?", a: "When the aircraft ahead is heavy, clean, and slow." },
    { topic: "Airports", q: "Avoiding wake turbulence landing/departing behind a larger aircraft?", a: "Landing: stay at/above its path and land beyond its touchdown point. Departing: rotate before its rotation point and climb above its path. Wait ~2 minutes." },
    { topic: "Airports", q: "Displaced threshold vs blast pad markings?", a: "Displaced threshold = white arrows leading to the threshold bar (no landing before it). Blast pad/stopway = yellow chevrons (no taxi, takeoff, or landing)." },
    { topic: "Airports", q: "Stabilized approach — target airspeed?", a: "The landing speed in the POH/AFM, held within +10 / −5 KIAS (constant ~3° descent)." },
    { topic: "Airports", q: "Soft-field landing — what approach speed?", a: "The same approach speed as a normal landing; the soft-field technique is in the touchdown (hold the nosewheel off), not the approach." },
    { topic: "Airports", q: "Short-field landing in gusty wind — speed adjustment?", a: "Add half the gust factor (gust speed − steady wind) to the approach speed." },
    // ATC
    { topic: "ATC", q: "VFR squawk code?", a: "1200." },
    { topic: "ATC", q: "Squawk 7500?", a: "Hijack." },
    { topic: "ATC", q: "Squawk 7600?", a: "Lost communications (no radio)." },
    { topic: "ATC", q: "Squawk 7700?", a: "Emergency." },
    { topic: "ATC", q: "What is Mode C?", a: "The transponder's ability to send altitude information to ATC." },
    { topic: "ATC", q: "Emergency / guard frequency?", a: "121.5 MHz (also used to check an ELT)." },
    { topic: "ATC", q: "Departure controller sequence?", a: "ATIS → Ground (taxi) → Tower (takeoff)." },
    { topic: "ATC", q: "What is the MULTICOM frequency?", a: "Always 122.9 — used to self-announce when a non-towered field has no tower, FSS, or UNICOM." },
    { topic: "ATC", q: "Unsure of the winds or active runway at a non-towered field?", a: "Call on the CTAF and request an airport advisory (from UNICOM or Flight Service)." },
    // Performance
    { topic: "Performance", q: "How does maneuvering speed (Va) change with weight?", a: "Heavier = higher Va; lighter = lower Va." },
    { topic: "Performance", q: "The four factors affecting performance?", a: "Altitude, temperature, pressure, humidity — all via air density." },
    { topic: "Performance", q: "Effect of high density altitude on takeoff and climb?", a: "Longer takeoff roll and a slower, shallower climb." },
    { topic: "Performance", q: "Define density altitude.", a: "Pressure altitude corrected for non-standard temperature." },
    { topic: "Performance", q: "Pressure altitude formula?", a: "Indicated altitude + (29.92 − altimeter setting) × 1,000 (or set the altimeter to 29.92)." },
    { topic: "Performance", q: "About 15 °F above standard equals how much density altitude?", a: "Roughly +1,000 ft (≈120 ft per °C)." },
    { topic: "Performance", q: "How much does 1 gallon of avgas weigh?", a: "About 6 lbs." },
    { topic: "Performance", q: "High pressure vs low pressure air?", a: "High = cool, sinking air (fair); low = warm, rising air (poorer performance)." },
    // Regulations
    { topic: "Regulations", q: "ARROW — documents required on board?", a: "Airworthiness cert, Registration, Radio license (intl), Operating limitations (POH), Weight & balance." },
    { topic: "Regulations", q: "Which required document must be displayed in the aircraft?", a: "Only the Airworthiness certificate (visible to passengers/crew). The rest just need to be aboard." },
    { topic: "Regulations", q: "VFR fuel reserves, day and night?", a: "Day: +30 minutes; Night: +45 minutes." },
    { topic: "Regulations", q: "VFR cruising altitude eastbound (0–179°)?", a: "Odd thousand + 500 ft." },
    { topic: "Regulations", q: "VFR cruising altitude westbound (180–359°)?", a: "Even thousand + 500 ft." },
    { topic: "Regulations", q: "Speed limit below 10,000 ft MSL?", a: "250 KIAS." },
    { topic: "Regulations", q: "Speed limit below 2,500 AGL within 4 NM of a C/D airport?", a: "200 KIAS." },
    { topic: "Regulations", q: "Minimum altitude over congested areas?", a: "1,000 ft above the highest obstacle within a 2,000 ft radius." },
    { topic: "Regulations", q: "Minimum altitude other than congested?", a: "500 ft AGL." },
    { topic: "Regulations", q: "Flight review interval?", a: "Every 24 calendar months." },
    { topic: "Regulations", q: "Passenger-carrying currency?", a: "3 takeoffs & landings in the last 90 days (full-stop at night)." },
    { topic: "Regulations", q: "3rd-class medical validity, under vs over 40?", a: "Under 40: 60 months. 40 and over: 24 months." },
    { topic: "Regulations", q: "Alcohol rule?", a: "8 hours bottle-to-throttle and BAC below 0.04." },
    { topic: "Regulations", q: "When are parachutes required?", a: "Intentionally exceeding 30° pitch or 60° bank with passengers (chute repacked within 180 days)." },
    { topic: "Regulations", q: "Annual vs 100-hour inspection?", a: "Annual every 12 months (all aircraft); 100-hour for aircraft for hire." },
    { topic: "Regulations", q: "Transponder and ELT inspection intervals?", a: "Transponder: 24 calendar months. ELT: 12 calendar months." },
    { topic: "Regulations", q: "ELT transmit frequencies?", a: "121.5 and 243.0 MHz (newer units also 406)." },
    { topic: "Regulations", q: "When may an ELT be tested?", a: "Only during the first 5 minutes after the hour." },
    { topic: "Regulations", q: "NTSB written accident report is due when?", a: "Within 10 days." },
    { topic: "Regulations", q: "May you move accident wreckage before the NTSB arrives?", a: "Only to protect it from further damage, protect the public, or free injured persons — otherwise preserve it." },
    { topic: "Regulations", q: "What must a preventive-maintenance record entry contain?", a: "A description of the work, the date, and the signature, certificate number, and kind of certificate held by the person approving the work." },
    { topic: "Regulations", q: "Type rating required above what weight?", a: "12,500 lbs (and turbojets)." },
    { topic: "Regulations", q: "High-performance vs complex airplane endorsement?", a: "High-performance = engine over 200 hp. Complex = retractable gear + flaps + controllable-pitch prop." },
    { topic: "Regulations", q: "BasicMed aircraft limits?", a: "Up to 7 occupants, max takeoff weight 12,500 lb, no more than 6 passengers; ≤18,000 ft MSL and ≤250 KIAS." },
    { topic: "Regulations", q: "Right-of-way: landing, and two aircraft approaching to land?", a: "Aircraft on final/landing have the right of way; of two approaching, the lower one has it — but don't cut in front of or overtake an aircraft on final." },
    { topic: "Regulations", q: "Emergency deviation — who do you report to (if asked)?", a: "Deviate from an ATC clearance/instruction → within 48 hr to the ATC facility manager. Deviate from a Part 91 rule → to the FAA Administrator. TCAS RA → notify ATC, no report." },
    { topic: "Regulations", q: "Can you drop objects from an aircraft in flight?", a: "Yes — if reasonable precautions are taken so it creates no hazard to persons or property (§91.15)." },
    { topic: "Regulations", q: "Tower in Class E/G airspace — when establish two-way radio?", a: "Before 4 NM from the airport and at/below 2,500 ft AGL." },
    // Weather
    { topic: "Weather", q: "Low-pressure rotation and vertical motion (N. Hem.)?", a: "Counterclockwise, inflow, rising air → clouds/bad weather." },
    { topic: "Weather", q: "High-pressure rotation and vertical motion?", a: "Clockwise, outflow, sinking air → fair weather." },
    { topic: "Weather", q: "The three ingredients for a thunderstorm?", a: "Sufficient moisture, lifting action, and unstable air." },
    { topic: "Weather", q: "The three stages of a thunderstorm?", a: "Towering cumulus, mature, dissipating." },
    { topic: "Weather", q: "Most hazardous thunderstorm stage?", a: "Mature stage (both updrafts and downdrafts)." },
    { topic: "Weather", q: "Stable air gives which clouds and conditions?", a: "Stratiform clouds, poor visibility, steady precip, smooth air." },
    { topic: "Weather", q: "Unstable air gives which clouds and conditions?", a: "Cumuliform clouds, good visibility, showers, turbulence." },
    { topic: "Weather", q: "How does radiation fog form?", a: "Ground cools below the dew point on clear, calm nights (after sunset)." },
    { topic: "Weather", q: "How does advection fog form?", a: "Wind carries moist air over a cooler surface (e.g. cool water)." },
    { topic: "Weather", q: "What does a temperature inversion produce?", a: "Stable air, poor visibility and fog (trapped beneath warmer air)." },
    { topic: "Weather", q: "Standard temperature lapse rate?", a: "About 2 °C per 1,000 ft." },
    { topic: "Weather", q: "The four front types?", a: "Warm, cold, stationary, occluded." },
    { topic: "Weather", q: "What do you notice flying across a front?", a: "A change in wind direction." },
    { topic: "Weather", q: "Where is clear air turbulence found?", a: "On the cold side of the jet stream, near the trough." },
    { topic: "Weather", q: "Does icing need visible moisture?", a: "Structural (airframe) icing does — visible moisture + freezing temps. Carburetor icing does NOT — just high humidity, so it can form in clear air." },
    // Weather Reports
    { topic: "Weather Reports", q: "METAR vs TAF?", a: "METAR = current observation; TAF = forecast." },
    { topic: "Weather Reports", q: "Sky cover, least to most?", a: "CLR → FEW → SCT → BKN → OVC." },
    { topic: "Weather Reports", q: "What counts as a ceiling?", a: "The lowest broken (BKN) or overcast (OVC) layer." },
    { topic: "Weather Reports", q: "FEW, SCT, BKN coverage in eighths?", a: "FEW 1–2/8, SCT 3–4/8, BKN 5–7/8 (OVC 8/8)." },
    { topic: "Weather Reports", q: "Maximum visibility a TAF reports?", a: "6 SM (shown as P6SM)." },
    { topic: "Weather Reports", q: "Decode winds aloft 730649.", a: "230° at 106 kts, −49 °C (code dir > 36 → subtract 50 from dir, add 100 to speed)." },
    { topic: "Weather Reports", q: "METAR codes BR, FG, HZ?", a: "Mist, fog, haze." },
    { topic: "Weather Reports", q: "AIRMET vs SIGMET?", a: "AIRMET = significant to light aircraft (turbulence/IFR/icing); SIGMET = severe, all aircraft." },
    { topic: "Weather Reports", q: "What does 'convective' mean in a forecast?", a: "Thunderstorms." },
    { topic: "Weather Reports", q: "When is an outlook briefing used?", a: "When departure is 6 or more hours away." },
    { topic: "Weather Reports", q: "What do you tell the briefer when requesting a weather briefing?", a: "That you're a pilot, whether it's VFR or IFR, and your aircraft ID (N-number) — plus route, altitude, and timing." },
    { topic: "Weather Reports", q: "What is a significant weather prog chart for?", a: "Forecasting hazards (IFR/MVFR areas, turbulence, freezing levels) by altitude block — to decide which areas and altitudes to avoid." },
    // Navigation
    { topic: "Navigation", q: "What is a VOR radial?", a: "A magnetic course FROM the station." },
    { topic: "Navigation", q: "CDI needle deflected right means?", a: "The selected course/station is to your right — fly toward the needle." },
    { topic: "Navigation", q: "No TO/FROM flag means?", a: "You're perpendicular to the radial." },
    { topic: "Navigation", q: "How do you get a position fix from VORs?", a: "Cross two FROM radials from two different stations." },
    { topic: "Navigation", q: "Key GPS limitation?", a: "It knows position and track, but not aircraft heading." },
    { topic: "Navigation", q: "What does RAIM do?", a: "Verifies that the GPS signal is still accurate (integrity)." },
    { topic: "Navigation", q: "'Read it / hear it' rule?", a: "If you read it, it's true; if you hear it, it's magnetic." },
    { topic: "Navigation", q: "NAVAID symbols: VOR, VORTAC, VOR/DME?", a: "Hexagon = VOR; hexagon + tabs = VORTAC; hexagon in a square = VOR/DME." },
    // Navigation Planning
    { topic: "Navigation Planning", q: "Applying variation: 'East is least, west is best' means?", a: "True → magnetic: add westerly variation, subtract easterly variation." },
    { topic: "Navigation Planning", q: "The speed-distance-time relationship?", a: "Distance = Speed × Time (so Speed = D ÷ T, Time = D ÷ S)." },
    { topic: "Navigation Planning", q: "What is 1 knot?", a: "1 nautical mile per hour (keep time in hours in the formulas)." },
    // Human Factors
    { topic: "Human Factors", q: "Hypoxia can begin above what altitude?", a: "About 8,000 ft." },
    { topic: "Human Factors", q: "Carbon monoxide poisoning causes?", a: "Loss of muscular power (plus headache, dizziness) — from the exhaust-fed heater." },
    { topic: "Human Factors", q: "Best night-vision technique?", a: "Off-center (peripheral) viewing and scanning — the center of vision is weak at night." },
    { topic: "Human Factors", q: "What illusion does haze cause?", a: "Objects appear farther away than they are (risk of a low approach)." },
    { topic: "Human Factors", q: "In IMC, acceleration and deceleration can feel like?", a: "A climb and a descent — trust the instruments." },
    { topic: "Human Factors", q: "Supplemental oxygen — 12,500 / 14,000 / 15,000 ft rules?", a: "Crew O₂ above 12,500 MSL after 30 min; crew at all times above 14,000; every occupant must be provided O₂ above 15,000." },
    { topic: "Human Factors", q: "What does IMSAFE stand for?", a: "Illness, Medication, Stress, Alcohol, Fatigue, Emotion/Eating." },
    { topic: "Human Factors", q: "The leans vs the Coriolis illusion?", a: "The leans = false sensation of banking (most common). Coriolis = abrupt head movement in a turn causes severe tumbling — avoid sudden head movements." },
    // ACS
    { topic: "ACS", q: "The 5 hazardous attitudes?", a: "Anti-authority, Impulsivity, Invulnerability, Macho, Resignation." },
    { topic: "ACS", q: "Antidotes — Macho and Invulnerability?", a: "Macho → 'taking chances is foolish.' Invulnerability → 'it could happen to me.'" },
    { topic: "ACS", q: "PAVE and DECIDE stand for?", a: "PAVE = Pilot, Aircraft, enVironment, External pressures. DECIDE = Detect, Estimate, Choose, Identify, Do, Evaluate." },
    { topic: "ACS", q: "What three things does risk management rely on?", a: "Situational awareness, problem recognition, and good judgment." },
    { topic: "ACS", q: "Airworthiness Directive vs SAIB?", a: "AD = mandatory; Special Airworthiness Information Bulletin = advisory only." },
    { topic: "ACS", q: "Spin recovery — PARE?", a: "Power idle, Ailerons neutral, Rudder full opposite the spin, Elevator forward to break the stall." },
    { topic: "ACS", q: "Lost procedure — the 5 C's?", a: "Climb, Communicate, Confess, Comply, Conserve (squawk 7700 if it's an emergency)." },
    { topic: "ACS", q: "Vacuum/gyro failure — which instruments are lost?", a: "Attitude indicator and heading indicator; turn coordinator, airspeed, altimeter, VSI and compass keep working (partial panel)." },
    { topic: "ACS", q: "A VFR flight plan — what must you do with it?", a: "Activate it with Flight Service after departure and close it on arrival; SAR begins 30 min after your ETA if you don't close it." },
    { topic: "ACS", q: "Runway Status Lights (RWSL)?", a: "Automatic red lights (REL/THL) independent of ATC — never enter or depart on red; a red light overrides an ATC clearance." },
    // Testing Supplement
    { topic: "Supplement", q: "Where do you look up density altitude on the test?", a: "Figure 8 — Density Altitude Chart (in the Airman Knowledge Testing Supplement)." },
    { topic: "Supplement", q: "Which figures decode a METAR and a TAF?", a: "Figure 12 (METAR) and Figure 15 (TAF)." },
    { topic: "Supplement", q: "Where do you read load factor for a bank angle?", a: "Figure 2 — Load Factor Chart (60° bank ≈ 2 G)." },
    { topic: "Supplement", q: "What do you use for sectional chart / airspace questions?", a: "Legend 1 (Sectional Aeronautical Chart) plus the Sectional Chart Excerpt figures." },
    { topic: "Supplement", q: "Where do you look up the pilot-controlled lighting clicks?", a: "Legend 9 (Chart Supplement directory legend): 7/5/3 mic clicks = high/medium/low intensity." },
    { topic: "Supplement", q: "Where can you find the magnetic variation for a location?", a: "Read the isogonic line off the sectional chart (Legend 1) — no need to memorize it." },
  ],
};
